name: Unit tests
on: [pull_request]

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # install python stuff
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        cache: 'pip'
    - name: Install Python dependencies
      run: |
        make dev-install-dependencies-pack
        make dev-install-dependencies-pack-sudo
        make dev-install-dependencies-for-development

    - name: Run unit tests
      run: python -m unittest discover -s TA_dataset/bin/tests
